### ISSUE TITLE
kivy installation on windows

### ISSUE THREAD

**Issue by psalrod** [KivyBrazil/kivy-forum#1]
I´m coding using python for the last 2 years and I decided to learn kivy on windows 7.
I´m running python on a linux PC (Mint 19 and now on Elementary 5), but after some problems in installing kivy on linux I decided to try on windows in another pc. That´s an old one with 9 years old and only 2 GB of RAM.
I have installed python 3.8.3 successfully. After that I followed the instructions on kivy.org website:
1. python -m pip install --upgrade pip wheel setuptools virtualenv
2. kivy_venv\Scripts\activate
3. python -m pip install docutils pygments pypiwin32 kivy_deps.sdl2==0.1.* kivy_deps.glew==0.1.*

All these steps were successful.

I´ve not installed gstreamer and angle.

The errors occurred on this step:
1. python -m pip install kivy==1.11.1

The first time I ran this command, I found a requirement to update Visual Studio. After install it and reboot the errors continued. The output is attached.

At the 2nd time running the command above I received a message saying that python has stopped.

Someone can helpme to set kivy?

[log.txt](https://github.com/KivyBrazil/kivy-forum/files/4893181/log.txt)

**Comment by VictorManhani** [comment]
Hello, @psairod, sorry for the delay!

This is happening because of the version of python currently installed on your machine. Kivy 1.11.1 only works with python 3.7.

To install kivy with the most current version of python (3.8), follow the tutorial with the URL below, as it explains step by step how to install kivy with the new version of the python.

Instalando Python 3.8.3, Kivy 2.0.0, VSCode e Criando App Inicial
https://www.youtube.com/watch?v=0ULVx7JXhlY&t=2s

It is in Portuguese, but you can follow it step by step by following the video.

Greetings from Brazil!
